- name: Install bind package
  package:
    name: bind9
    state: present

- name: Stop systemd-resolved
  systemd:
    state: stopped
    name: systemd-resolved
    enabled: false
    daemon_reload: true

- name: Copy named.conf
  copy:
    src: named.conf
    dest: /etc/bind/named.conf.options

- name: Ensure named dir exists
  file:
    path: /etc/bind/custom
    state: directory

- name: Start bind
  systemd:
    state: restarted
    name: named
    enabled: true
    daemon_reload: yes

- name: Ensure resolv.conf is mutable
  when: immutable_resolve is defined
  file:
    path: /etc/resolv.conf
    attr: -i

- name: Sync resolv.conf file
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure resolv.conf is immutable
  file:
    path: /etc/resolv.conf
    attr: +i
  register: immutable_resolve
