- name: Sync {{ job_name }} job configs
  synchronize:
    src: "../templates/{{ job_dir }}"
    dest: "{{ nomad.remote.jobs.root_dir }}/"
    rsync_opts:
      - "--exclude=job.hcl"
      - "--chmod=F600"
      - "--chown=nomad:nomad"

- name: Ensure directory has proper chmod
  file:
    path: "{{ nomad.remote.jobs.root_dir }}/{{ job_name }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0700

- name: Sync job file
  template:
    src: "{{ job_dir }}/job.hcl"
    dest: "{{ nomad.remote.jobs.root_dir }}/{{ job_name }}/job.hcl"
    owner: nomad
    group: nomad
    mode: 0600

- name: Apply {{ job_name }} to cluster
  become_user: nomad
  shell: |
    nomad job run \
        -address=https://localhost:4646 \
        -ca-path=/var/www/nomad/tls/nomad-ca.pem \
        -client-cert=/var/www/nomad/tls/server.pem \
        -client-key=/var/www/nomad/tls/server-key.pem \
        -token=$(jq -r '.SecretID' /var/www/nomad/server/bootstrap.json) \
        {{ nomad.remote.jobs.root_dir + '/' + job_name + '/job.hcl' }}
