- name: Read consul token
  slurp:
    src: "{{ nomad.remote.server.root_dir + '/server.env' }}"
  register: server_env

- name: Set vars
  set_fact:
    remote_job_dir: "{{ nomad.remote.jobs.root_dir }}/{{ job_name }}"
    consul_token: "{{ server_env.content | b64decode | regex_search('CONSUL_HTTP_TOKEN=(.+)[$\n]', '\\1') | first }}"

- name: Ensure directory has proper chmod
  file:
    path: "{{ remote_job_dir }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0700

- name: Sync all templates
  template:
    src: "{{ file }}"
    dest: "{{ remote_job_dir }}/"
    owner: nomad
    group: nomad
    mode: 0600
  loop_control:
    loop_var: file
  with_fileglob:
    - "{{ job_dir }}/*"

- name: Apply {{ job_name }} to cluster
  become_user: nomad
  shell: |
    nomad job run \
        -address=https://localhost:4646 \
        -ca-path=/var/www/nomad/tls/nomad-ca.pem \
        -client-cert=/var/www/nomad/tls/server.pem \
        -client-key=/var/www/nomad/tls/server-key.pem \
        -token=$(jq -r '.SecretID' /var/www/nomad/server/bootstrap.json) \
        {{ nomad.remote.jobs.root_dir + '/' + job_name + '/job.hcl' }}
