- name: Ensure docker job dir exists
  file:
    path: "{{ remote_job_dir }}/docker"
    state: directory
    owner: nomad
    group: nomad
    mode: 0700

- name: Check if docker local dir exists
  become: false
  delegate_to: localhost
  register: docker_configs_dir
  stat:
    path: "{{ job_dir }}/docker"

- name: Sync all docker files
  when: docker_configs_dir.stat.isdir is defined and docker_configs_dir.stat.isdir
  template:
    src: "{{ file }}"
    dest: "{{ remote_job_dir }}/docker/"
    owner: nomad
    group: nomad
    mode: 0600
  loop_control:
    loop_var: file
  with_fileglob:
    - "{{ job_dir }}/docker/*"

- name: Build and push docker compose
  shell: |
    cd {{ remote_job_dir }}/
    docker compose build --parallel
    docker compose push
