- name: Ensure jobs dir present
  file:
    path: "{{ nomad.remote.jobs.root_dir }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0755

- name: Deploy core jobs
  include_tasks: deploy-job.yml
  vars:
    job_dir: "{{ nomad.local.jobs.root_dir }}/core/{{ item }}"
    job_name: "{{ item }}"
  with_items:
    - docker-registry
    - reverse-proxy

- name: Deploy databases jobs
  include_tasks: deploy-job.yml
  vars:
    job_dir: "{{ nomad.local.jobs.root_dir }}/databases/{{ item }}"
    job_name: "{{ item }}"
  with_items:
    - postgres
    - elasticsearch
    - redis
