- name: Ensure jobs dir present
  file:
    path: "{{ nomad.remote.jobs.root_dir }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0755

- name: Deploy jobs
  include_tasks: deploy-job.yml
  vars:
    job_dir: "{{ item }}"
    job_name: "{{ item | split('/') | last }}"
  with_items:
    - "jobs/hello-world"
