server: front

docker:
  volumes_path: "{{ remote_paths.www }}/volumes"

all_groups:
  - name: webusers
  - name: deployusers
  - name: docker

all_users:
  - name: ci
    groups: webusers,deployusers,docker

  - name: deploy
    groups: deployusers,webusers,wheel,docker

  - name: web
    groups: webusers

consul:
  local:
    acl_dir: "{{ local_paths.all_keys }}/consul/acl"

    encryption:
      gossip: "{{ lookup('file', local_paths.all_keys + '/consul/gossip-encryption.key') }}"

    server:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/consul/tls/server"
        ca_dir: "{{ local_paths.all_keys }}/consul/tls/ca"

    client:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/consul/tls/client"

  remote:
    root_dir: "{{ remote_paths.www }}/consul"
    tls_dir: "{{ remote_paths.www }}/consul/tls"
    tokens_dir: "{{ remote_paths.www }}/consul/tokens"
    acl_dir: "{{ remote_paths.www }}/consul/acl"

    server:
      root_dir: "{{ remote_paths.www }}/consul/server"

    client:
      root_dir: "{{ remote_paths.www }}/consul/client"

nomad:
  local:
    server:
      token: "{{ lookup('file', local_paths.all_keys + '/nomad/token.key') }}"
      tls:
        ca_dir: "{{ local_paths.all_keys }}/nomad/tls/ca"
        keys_dir: "{{ local_paths.all_keys }}/nomad/tls/server"

    client:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/nomad/tls/client"

  remote:
    advert_real_ip: "{{ ansible_eth1.ipv4.address }}"
    root_dir: "{{ remote_paths.www }}/nomad"
    tls_dir: "{{ remote_paths.www }}/nomad/tls"

    jobs:
      root_dir: "{{ remote_paths.www }}/jobs"

    server:
      root_dir: "{{ remote_paths.www }}/nomad/server"

    client:
      root_dir: "{{ remote_paths.www }}/nomad/client"
