server: front

cluster_hostname: upolujksiazke.pl

docker:
  volumes_path: "{{ remote_paths.www }}/volumes"
  registry:
    credentials: "{{ lookup('file', local_paths.all_keys + '/docker/registry-credentials.json') | from_json }}"

nfs:
  app_data_dir: "{{ docker.volumes_path }}/app-data"

all_groups:
  - name: wheel
  - name: webusers
  - name: deployusers
  - name: docker

all_users:
  - name: ci
    groups: webusers,deployusers,docker

  - name: deploy
    groups: deployusers,webusers,wheel,docker

  - name: web
    groups: webusers

consul:
  local:
    acl_dir: "{{ local_paths.all_keys }}/consul/acl"

    encryption:
      gossip: "{{ lookup('file', local_paths.all_keys + '/consul/gossip-encryption.key') }}"

    server:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/consul/tls/server"
        ca_dir: "{{ local_paths.all_keys }}/consul/tls/ca"

    client:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/consul/tls/client"

  remote:
    root_dir: "{{ remote_paths.www }}/consul"
    tls_dir: "{{ remote_paths.www }}/consul/tls"
    tokens_dir: "{{ remote_paths.www }}/consul/tokens"
    acl_dir: "{{ remote_paths.www }}/consul/acl"

    server:
      root_dir: "{{ remote_paths.www }}/consul/server"

    client:
      root_dir: "{{ remote_paths.www }}/consul/client"

nomad:
  local:
    jobs:
      root_dir: "{{ local_paths.project }}/jobs"

    server:
      token: "{{ lookup('file', local_paths.all_keys + '/nomad/token.key') }}"
      tls:
        ca_dir: "{{ local_paths.all_keys }}/nomad/tls/ca"
        keys_dir: "{{ local_paths.all_keys }}/nomad/tls/server"

    client:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/nomad/tls/client"

  remote:
    root_dir: "{{ remote_paths.www }}/nomad"
    tls_dir: "{{ remote_paths.www }}/nomad/tls"

    jobs:
      root_dir: "{{ remote_paths.www }}/jobs"

    server:
      root_dir: "{{ remote_paths.www }}/nomad/server"

    client:
      root_dir: "{{ remote_paths.www }}/nomad/client"

vault:
  local:
    server:
      policies_dir: "{{ local_paths.all_keys }}/vault/policies"
      backup_dir: "{{ local_paths.all_keys }}/vault/backup"

      tls:
        ca_dir: "{{ local_paths.all_keys }}/vault/tls/ca"
        keys_dir: "{{ local_paths.all_keys }}/vault/tls/server"
    client:
      tls:
        keys_dir: "{{ local_paths.all_keys }}/vault/tls/client"

  remote:
    root_dir: "{{ remote_paths.www }}/vault"
    tls_dir: "{{ remote_paths.www }}/vault/tls"

    server:
      root_dir: "{{ remote_paths.www }}/vault/server"
      tokens_dir: "{{ remote_paths.www }}/vault/tokens"
      policies_dir: "{{ remote_paths.www }}/vault/policies"

    client:
      tokens_dir: "{{ remote_paths.www }}/vault/tokens"
