[log]
level = "debug"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.traefik]
  address = ":8081"

[api]
  dashboard = true
  insecure = true

[providers.consulCatalog]
  prefix = "traefik"
  exposedByDefault = false

  [providers.consulCatalog.endpoint]
  address = "127.0.0.1:8500"
  scheme = "http"
  token = "{{ consul_token }}"
