- name: Copy nomad-server systemd service
  register: nomad_server_service
  template:
    src: nomad-server.service
    dest: /etc/systemd/system/nomad-server.service
    owner: root
    group: root
    mode: 0755

- name: Create nomad server data dir
  file:
    path: "{{ nomad.remote.server.root_dir }}/data"
    state: directory
    owner: nomad
    group: nomad
    mode: 0755

- name: Copy nomad server TLS keys
  register: nomad_server_tls_keys
  copy:
    src: "{{ item }}"
    dest: "{{ nomad.remote.tls_dir }}/"
    owner: nomad
    group: nomad
    mode: 0600
  with_fileglob:
    - "{{ nomad.local.server.tls.keys_dir }}/*"

- name: Copy nomad CA key
  register: nomad_server_ca_key
  copy:
    src: "{{ nomad.local.server.tls.ca_dir }}/nomad-ca.pem"
    dest: "{{ nomad.remote.tls_dir }}/"
    owner: nomad
    group: nomad
    mode: 0600

- name: Copy nomad token file
  register: nomad_server_token
  copy:
    dest: "{{ nomad.remote.server.root_dir }}/token.key"
    content: "{{ nomad.local.server.token }}"
    owner: nomad
    group: nomad
    mode: 0600

- name: Copy server config
  register: nomad_server_config
  template:
    src: server.hcl
    dest: "{{ nomad.remote.server.root_dir }}/config.hcl"
    owner: nomad
    group: nomad
    mode: 0600

- name: Copy nomad server env
  register: nomad_server_env
  template:
    src: server.env
    dest: "{{ nomad.remote.server.root_dir }}/server.env"
    owner: nomad
    group: nomad
    mode: 0600

- name: Start nomad-server systemd service
  when: >
    nomad_server_service.changed or
    nomad_server_tls_keys.changed or
    nomad_server_ca_key.changed or
    nomad_server_token.changed or
    nomad_server_config.changed or
    nomad_server_env.changed
  systemd:
    name: nomad-server
    state: restarted
    enabled: true
    daemon_reload: yes

- name: Wait for server to be ready...
  pause:
    seconds: 7

- name: Bootstrap server acl
  args:
    executable: /bin/bash
  shell: |
    # Reset previous key
    bootstrap_index=$(jq -r '.CreateIndex' {{ nomad.remote.server.root_dir }}/bootstrap.json 2>/dev/null)
    if [[ ! -z "$bootstrap_index" ]]; then
      echo "$bootstrap_index" > {{ nomad.remote.server.root_dir }}/data/server/acl-bootstrap-reset
    fi

    # Create new bootstrap file
    [ -e {{ nomad.remote.server.root_dir }}/bootstrap.json ] && rm {{ nomad.remote.server.root_dir }}/bootstrap.json
    bootstrap_result=$(
      nomad acl bootstrap \
        -json \
        -address=https://localhost:4646 \
        -ca-path={{ nomad.remote.tls_dir }}/nomad-ca.pem \
        -client-cert={{ nomad.remote.tls_dir }}/server.pem \
        -client-key={{ nomad.remote.tls_dir }}/server-key.pem \
        {{ nomad.remote.server.root_dir }}/token.key 2>/dev/null
    )

    if [[ ! -z "$bootstrap_result" ]]; then
      echo "$bootstrap_result" > {{ nomad.remote.server.root_dir }}/bootstrap.json
      chown nomad:nomad {{ nomad.remote.server.root_dir }}/bootstrap.json
      chmod 0600 {{ nomad.remote.server.root_dir }}/bootstrap.json
    fi
