- hosts: web
  gather_facts: false
  tasks:
    - name: Wait for SSH
      wait_for_connection:
        delay: 0
        timeout: 4000

- hosts: web
  tags: common
  gather_facts: true
  become: true
  module_defaults:
    apt:
      install_recommends: no
  roles:
    - role: common/firewall
    - role: common/dns
    - role: common/utils
    - role: common/sshd
    - role: common/users
    - role: common/fish
    - role: common/fail2ban
    - role: common/node
    - role: common/www

- hosts: cluster
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: cluster/cni
    - role: cluster/docker/daemon
    - role: cluster/docker/skeleton
    - role: cluster/nomad/shared
    - role: cluster/consul/shared

- hosts: server
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: cluster/consul/server
    - role: cluster/nomad/server

- hosts: client
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: cluster/consul/client
    - role: cluster/nomad/client

- hosts: server
  tags:
    - cluster
    - deploy
  gather_facts: true
  become: true
  roles:
    - role: cluster/jobs/deploy
