- hosts: cluster
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: common/network

    - role: cluster/nomad/shared
      tags: nomad

    - role: cluster/consul/shared
      tags: consul

    - role: cluster/vault/shared
      tags: vault

- hosts: server
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: cluster/consul/server
      tags: consul

    - role: cluster/vault/server
      tags: vault

    - role: cluster/nomad/server
      tags: nomad

- hosts: client
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: cluster/consul/client
      tags: consul

    - role: cluster/vault/client
      tags: vault

    - role: cluster/nomad/client
      tags: nomad

- hosts: cluster
  become: true
  tasks:
    - name: Wait for all nodes to be ready...
      pause:
        seconds: 15

- hosts: server
  tags:
    - cluster
    - deploy
  gather_facts: true
  become: true
  roles:
    - role: cluster/jobs/deploy
