- name: Install vault package
  package:
    name: vault
    state: present

- name: Ensure vault group present
  group:
    name: vault
    state: present

- name: Ensure vault user present
  user:
    name: vault
    groups: vault
    shell: /bin/bash
    append: yes

- name: Ensure vault dir present
  file:
    path: "{{ vault.remote.root_dir }}"
    state: directory
    owner: vault
    group: vault
    mode: 0755

- name: Ensure vault tls dir is present
  file:
    path: "{{ vault.remote.tls_dir }}"
    state: directory
    owner: vault
    group: vault
    mode: 0755
