name: Full infrastructure deploy

on:
  push:
    branches: [production]

concurrency:
  group: 'infrastructure-deploy'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Fetch config from S3 AWS
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ${{ secrets.AWS_CONFIG_BUCKET_FILE_URL }}
          destination: ./keys.tar
          aws_access_key_id: ${{ secrets.AWS_CONFIG_BUCKET_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_CONFIG_BUCKET_ACCESS_KEY }}
          aws_region: eu-central-1

      - name: Extract ansible config
        run: |
          rm -rf keys/*
          tar -zxf keys.tar -C ./keys

      - name: Install pulumi dependencies
        working-directory: pulumi/hetzner/nomad-cluster
        run: yarn install --frozen-lockfile

      - name: Pulumi deploy configuration
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          work-dir: pulumi/hetzner/nomad-cluster
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
